sudo: required

services:
  - docker

language: scala

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

scala:
  - 2.11.8

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^ICT-.*$/

before_install:
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeRestart;

script:
  - cp -n .env.example .env
  - sbt ++$TRAVIS_SCALA_VERSION test;

after_script:
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop;