sudo: required

services:
  - docker

language: scala

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

scala:
  - 2.11.8

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^ICT-.*$/

before_install:
  - if [[ -e ~/docker/postgres.tar ]]; then docker load -i ~/docker/postgres.tar; fi
  - if [[ -e ~/docker/java.tar ]]; then docker load -i ~/docker/java.tar; fi
  - if [[ -e ~/docker/kafka.tar ]]; then docker load -i ~/docker/kafka.tar; fi
  - if [[ -e ~/docker/zookeeper.tar ]]; then docker load -i ~/docker/zookeeper.tar; fi
  - if [[ -e ~/docker/feed.tar ]]; then docker load -i ~/docker/feed.tar; fi
  - IFS=',' read -r -a array <<< "java,test/postgres,exmaple/kafka,cool/zookeeper,wake/feed"; 
    for i in "${array[@]}"
    do
    echo "${i#*/}"
    done

before_script:
  - cp -n $TRAVIS_BUILD_DIR/.env.example $TRAVIS_BUILD_DIR/.env
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeRestart;

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travisci/jvmopts test;
  - mkdir -p ~/docker;
  - docker save $(docker history -q postgres:latest | grep -v '<missing>') > ~/docker/postgres.tar
  - docker save $(docker history -q java:latest | grep -v '<missing>') > ~/docker/java.tar
  - docker save $(docker history -q wurstmeister/kafka:latest | grep -v '<missing>') > ~/docker/kafka.tar
  - docker save $(docker history -q wurstmeister/zookeeper:latest | grep -v '<missing>') > ~/docker/zookeeper.tar
  - docker save $(docker history -q ekino/wiremock:latest | grep -v '<missing>') > ~/docker/feed.tar
  - find $HOME/.sbt -name "*.lock" | xargs rm 
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_cache: 
  # Tricks to avoid unnecessary cache updates 
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete 
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/docker
    - $HOME/.ivy2/cache 
    - $HOME/.sbt/boot/

after_script:
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop;
