sudo: required

services:
  - docker

language: scala

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

scala:
  - 2.11.8

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

before_install:
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeRestart;

script:
  - sbt ++$TRAVIS_SCALA_VERSION test;