sudo: required

services:
  - docker

language: scala

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

scala:
  - 2.11.8

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^ICT-.*$/

before_install:
  - if [[ ( "$DOWNLOAD_DOCKER_IMAGE" = true ) && ( -d "$HOME/docker" ) ]]; then rm -rf $HOME/docker/*.tar; fi
  - IFS=',' read -r -a images <<< $DOCKER_IMAGES;
    for i in "${images[@]}";
    do
      if [[ ( -e $HOME/docker/${i#*/}.tar ) && ( "$DO_E2E_TESTS" = true ) ]]; then docker load -i $HOME/docker/"${i#*/}".tar; fi
    done

before_script:
  - cp -n $TRAVIS_BUILD_DIR/.env.example $TRAVIS_BUILD_DIR/.env
  - if [[ ( "$DO_E2E_TESTS" = true ) ]]; then
      sbt ++$TRAVIS_SCALA_VERSION dockerComposeRestart;
    fi

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travisci/jvmopts test;
  - mkdir -p $HOME/docker;
  - IFS=',' read -r -a images <<< $DOCKER_IMAGES;
    for i in "${images[@]}";
    do
    container=$(docker history -q $i:latest | grep -v '<missing>');
    if [[ ( ! -e $HOME/docker/${i#*/}.tar ) && ( -n "$container" ) ]]; then
      docker save $container > $HOME/docker/${i#*/}.tar;
    fi
    done
  - find $HOME/.sbt -name "*.lock" | xargs rm 
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_cache: 
  # Tricks to avoid unnecessary cache updates 
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete 
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/docker
    - $HOME/.ivy2/cache 
    - $HOME/.sbt/boot/

after_script:
  - if [[ ( "$DO_E2E_TESTS" = true ) ]]; then
      sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop;
    fi

env:
  global:
    - DOCKER_IMAGES=java,postgres,wurstmeister/kafka,wurstmeister/zookeeper,ekino/wiremock
    - DOWNLOAD_DOCKER_IMAGE=false
  matrix:
    - DO_E2E_TESTS=true
    - DO_E2E_TESTS=false
