sudo: required

services:
  - docker

language: scala

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

scala:
  - 2.11.8

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^ICT-.*$/

before_script:
  - cp -n $TRAVIS_BUILD_DIR/.env.example $TRAVIS_BUILD_DIR/.env
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeRestart;

script:
  - sbt ++$TRAVIS_SCALA_VERSION test;

after_script:
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop;

notifications:
  email:
    on_success: always
    on_failure: always