sudo: required

services:
  - docker

language: scala

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

scala:
  - 2.11.8

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^ICT-.*$/

before_script:
  - cp -n $TRAVIS_BUILD_DIR/.env.example $TRAVIS_BUILD_DIR/.env
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeRestart;
  - docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${docker ps -ps "name=kafka"}

script:
  - sbt ++$TRAVIS_SCALA_VERSION test;

after_script:
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop;