sudo: required

services:
  - docker

language: scala

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

scala:
  - 2.11.8

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^ICT-.*$/

before_install:
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi

before_script:
  - cp -n $TRAVIS_BUILD_DIR/.env.example $TRAVIS_BUILD_DIR/.env
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeRestart;

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travisci/jvmopts test;
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    mkdir -p $(dirname ${DOCKER_CACHE_FILE});
    docker save $(docker history -q postgres:latest | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE};
    fi

cache:
  directories:
    - ${HOME}/docker

after_script:
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop;

env:
  global:
    - DOCKER_CACHE_FILE=${HOME}/docker/cache.tar.gz