sudo: required

services:
  - docker

language: scala

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

scala:
  - 2.11.8

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^ICT-.*$/

before_install:
  #- if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi
  #- if [ -f ${DOCKER_JAVA_FILE} ]; then gunzip -c ${DOCKER_JAVA_FILE} | docker load; fi
  - if [[ -e ~/docker/postgres.tar ]]; then docker load -i ~/docker/postgres.tar; fi
  - if [[ -e ~/docker/java.tar ]]; then docker load -i ~/docker/java.tar; fi

before_script:
  - cp -n $TRAVIS_BUILD_DIR/.env.example $TRAVIS_BUILD_DIR/.env
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeRestart;

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travisci/jvmopts test;
  #- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  #  mkdir -p $(dirname ${DOCKER_CACHE_FILE});
  #  docker save $(docker history -q postgres:latest | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE};
  #  mkdir -p $(dirname ${DOCKER_JAVA_FILE});
  #  docker save $(docker history -q java:latest | grep -v '<missing>') | gzip > ${DOCKER_JAVA_FILE};
  #  fi
  - mkdir -p ~/docker;
  - docker save $(docker history -q postgres:latest | grep -v '<missing>') > ~/docker/postgres.tar
  - docker save $(docker history -q java:latest | grep -v '<missing>') > ~/docker/java.tar
  - find $HOME/.sbt -name "*.lock" | xargs rm 
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_cache: 
  # Tricks to avoid unnecessary cache updates 
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete 
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/docker
    - $HOME/.ivy2/cache 
    - $HOME/.sbt/boot/

after_script:
  - sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop;

env:
  global:
    - DOCKER_CACHE_FILE=${HOME}/docker/postgres.tar
    - DOCKER_JAVA_FILE=${HOME}/docker/java.tar