version: '2'
services:
  postgres:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5431:5432"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "com.timeout.feeds.Venues:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  feeds:
    image: ekino/wiremock
    ports:
      - "9090:8080"
    volumes:
      - ./wiremock/files:/wiremock/__files
      - ./wiremock/mappings:/wiremock/mappings
